accepted_ranks: [genus, subgenus, species, subspecies, variety, form]
aggregation_level: species
bioclim_extent: [-180, 180, -60, 90]
bioclim_sensitivity_nb_samples: 50
bioclim_suitability_grid_resolution: 200
bioclim_suitability_max_error: 0.1
download_date: 2021-04-14
ecoregions_download_url: http://maps.tnc.org/files/shp/terr-ecoregions-TNC.zip
envirem_bioclim_download_url: https://deepblue.lib.umich.edu/data/downloads/ms35t870p?locale=en
envirem_topo_download_url: https://deepblue.lib.umich.edu/data/downloads/37720c880?locale=en
folder_structure:
  manual_data: data
  raw_data: data/raw
  processed_data: data/processed
  cache: data/cache
  stan_sources: stan/src
  stan_binaries: stan/bin
  results_bioclim: results/bioclim
  results_simulations: results/simulations
fun_groups_plausible_kingdoms:
  Anemone: [Animalia]
  Ant: [Animalia]
  Consumer: [Animalia, Plantae, Fungi, Other Eukaryota, Bacteria, Archaea]
  Disperser: [Animalia]
  Fish: [Animalia]
  Herbivore: [Animalia]
  Host: [Animalia]
  Parasite: [Animalia, Fungi, Other Eukaryota, Bacteria, Archaea]
  Plant: [Plantae]
  Pollinator: [Animalia]
  Resource: [Animalia, Plantae, Fungi, Other Eukaryota, Bacteria, Archaea]
itis_download_url: https://www.itis.gov/downloads/itisSqlite.zip
min_locations_per_species: 2
stan_simulations_specs:
  - name: pol_logit_c01
    data_generation_model: pol_logit_c
    data_generation_args:
      nb_pla: 43
      nb_pol: 87
      nb_sites: 15
    stan_model: pol_logit_c
    chains: 4
    stan_sample_args:
      iter_warmup: 1000
      iter_sampling: 2000
      refresh: 250
  - name: pol_logit_d01
    data_generation_model: pol_logit_d
    data_generation_args:
      nb_pla: 43
      nb_pol: 87
      nb_sites: 15
    stan_model: pol_logit_d
    chains: 4
    stan_sample_args:
      iter_warmup: 1000
      iter_sampling: 2000
      refresh: 250
tex_folders_to_compile:
  - manuscript/outline/2021-04-07
wol_aquatic_networks: [FW_004, FW_005, FW_006, FW_008, FW_011, FW_012, FW_013, FW_014, FW_015, M_AF_001, M_AF_002]
wol_interaction_type: All
worldclim_download_url: https://data.biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_2.5m_bio.zip
