aggregation_level: species
download_date: 2021-04-14
ecoregions_download_url: http://maps.tnc.org/files/shp/terr-ecoregions-TNC.zip
envirem_bioclim_download_url: https://deepblue.lib.umich.edu/data/downloads/ms35t870p?locale=en
envirem_topo_download_url: https://deepblue.lib.umich.edu/data/downloads/37720c880?locale=en
fun_groups_plausible_kingdoms:
  Anemone: [Animalia]
  Ant: [Animalia]
  Consumer: [Animalia, Plantae, Fungi, Other Eukaryota, Bacteria, Archaea]
  Disperser: [Animalia]
  Fish: [Animalia]
  Herbivore: [Animalia]
  Host: [Animalia]
  Parasite: [Animalia, Fungi, Other Eukaryota, Bacteria, Archaea]
  Plant: [Plantae]
  Pollinator: [Animalia]
  Resource: [Animalia, Plantae, Fungi, Other Eukaryota, Bacteria, Archaea]
itis_download_url: https://www.itis.gov/downloads/itisSqlite.zip
min_locations_per_species: 2
tex_folders_to_compile:
  - manuscript/outline/2021-04-07
wol_aquatic_networks: [FW_004, FW_005, FW_006, FW_008, FW_011, M_AF_001, M_AF_002]
wol_fun_groups_info_path: data/wol_fun_groups_info.csv
wol_interaction_type: All
wol_manual_locations_path: data/wol_manual_locations.csv
wol_manual_species_names_path: data/wol_manual_species_names.csv
wol_supp_data_names_path: data/wol_supp_data_names.txt
worldclim_download_url: https://data.biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_2.5m_bio.zip
