download_date: 2021-04-14
ecoregions_download_url: http://maps.tnc.org/files/shp/terr-ecoregions-TNC.zip
itis_download_url: https://www.itis.gov/downloads/itisSqlite.zip
tex_folders_to_compile:
  - manuscript/outline/2021-04-07
wol_interaction_type: All
worldclim_download_url: https://data.biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_2.5m_bio.zip
